### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by yurivict** [salilab/rmf#125]
The last release was in 2014. Many commits were made after it.
The automatic system keeps recommending 1.1, but it probably isn't close to the latest code.

**Comment by benmwebb** [comment]
We don't make independent releases of RMF any more - they are included in [IMP](https://integrativemodeling.org).

**Comment by yurivict** [comment]
```imp``` is a big package, ```rmf``` is just used there. What if some other package would need to use ```rmf```. For example, ```chimera``` uses it, etc. I've created the ```rmf``` port because I want to port ```chimera``` to FreeBSD, and discovered this problem.

**Comment by benmwebb** [comment]
If you want to use RMF in your own projects, the head of the develop branch is considered stable. This is certainly what is used in IMP and Chimera.
