### ISSUE TITLE
RMF-medium_test_backwards.py fails with Timeout

### ISSUE THREAD

**Issue by yurivict** [salilab/rmf#126]
```
      Start 43: RMF-medium_test_backwards.py
 4/47 Test #43: RMF-medium_test_backwards.py ...........***Timeout  15.01 sec
```

OS: FreeBSD 12.2

Other testcases pass.

**Comment by benmwebb** [comment]
The default test timeouts might not be long enough, particularly if you run on an older or loaded machine.  You can increase the medium test timeouts by setting  the `IMP_MEDIUM_TIMEOUT` CMake cache variable, or skip them entirely by running `ctest -L CHEAP`.
