### ISSUE TITLE
Handle mismatched static info in rmf_cat

### ISSUE THREAD

**Issue by benmwebb** [salilab/rmf#128]
@alatham13

`rmf_cat` simply copies the static frame from the first RMF to the output file, then adds all non-static frames from all RMFs to the output. This generates incorrect RMFs and/or loses information when the static frames in the input RMFs are different.

For example, a rigid body is typically handled by storing component body-frame coordinates in the static frame, and the body's reference frame (which changes during a simulation) to the non-static frames. If these body-frame coordinates are different in the input RMF files (for example, if a different initial reference frame and thus mapping from global to body-frame coordinates was chosen) then the output RMF will include some non-static reference frames which don't match the static body-frame coordinates.

`rmf_cat` should check for mismatched static frames and warn or error out in the general case. For the specific case of rigid bodies, in principle the non-static reference frames could be transformed to match the static coordinates.

**Comment by alatham13** [comment]
This is great, thanks @benmwebb!
